version: "3"

services:
    rabbitmq_1:
        build: ./rabbit_mq
        ports:
            - 5672:5672
            - 15672:15672
        tty: true
    
    python_server:
        build: ./python_serve


networks:
    default:

    # now both services are binded through network
    # being inside of python_server container we can ping rabbitmq_1
    # by running ping rabbitmq_1
    # and running python send.py we eventually send data to 
    # rabbitmq_1 container